resources:
  - name: ownmavenhelloworld
    type: git
    source:
      uri: https://github.com/PaSaranya/mavenhelloworld.git
     
 
 
jobs:
  - name: build
    plan:
      - get: ownmavenhelloworld
        trigger: true
     
      - task: build
        privileged: true
        file: mavenhelloworld/ci/build.yml
